version: 2.1

executors:
  ci-executor:
    docker:
      - image: circleci/node:12.18.2-stretch-browsers

references:
  npm_cache_key: &npm_cache_key dependency-npm-{{ checksum "yarn.lock" }}-v1
  save_node_modules: &save_node_modules
    save_cache:
      key: *npm_cache_key
      paths:
        - node_modules
  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *npm_cache_key

jobs:
  install-packages:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start installing the packages"
      - *restore_node_modules
      - run: yarn install
      - *save_node_modules

  lint:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start lint"
      - *restore_node_modules
      - run: yarn lint

  format:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start Prettier"
      - *restore_node_modules
      - run: yarn prettier:check

  build:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start build"
      - *restore_node_modules
      - run: yarn build

  test:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start test"
      - *restore_node_modules
      - run: yarn test --watch false
      - store_artifacts:
          path: coverage

  e2e:
    executor: ci-executor
    steps:
      - checkout
      - run: echo "Start e2e"
      - *restore_node_modules
      - run: yarn e2e

workflows:
  version: 2
  build_and_test:
    jobs:
      - install-packages
      - lint:
          requires:
            - install-packages
      - format:
          requires:
            - install-packages
      - build:
          requires:
            - lint
            - format
      - test:
          requires:
            - lint
            - format
      # - e2e:
      #     requires:
      #       - lint
      #       - format
