name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ['CI']
    branches: [master]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'

      - name: Deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          yarn
          yarn ng deploy --base-href=/angular-architecture/ --name=${{ secrets.GH_USER_NAME }} --email=${{ secrets.GH_EMAIL }}
